basePath: /api/v1
definitions:
  models.UserInDB:
    properties:
      hashed_password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      parameters:
      - description: username
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: password
        in: body
        name: password
        required: true
        schema:
          type: string
      responses:
        "200":
          description: access_token
          schema:
            type: string
        "400":
          description: Invalid request body
          schema:
            type: string
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /users:
    post:
      consumes:
      - application/json
      description: Add a new user to the database
      parameters:
      - description: Username and hashed password
        in: body
        name: userInDB
        required: true
        schema:
          $ref: '#/definitions/models.UserInDB'
      produces:
      - application/json
      responses:
        "200":
          description: User added successfully
          schema:
            type: string
        "400":
          description: Invalid request payload
          schema:
            type: string
      summary: Add a new user
  /users/:name:
    get:
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      responses: {}
swagger: "2.0"
